config/routes.rb
Rails.application.routes.draw do
  get 'games/settings', to: 'games#settings'
  get 'games/score'
  get 'scores/result', to: 'scores#result', as: 'scores_result'
  post 'games/score', to: 'games#score'
  post 'scores/score', to: 'games#score'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'json'
require 'open-uri'

class GamesController < ApplicationController
  def settings
    @letters = generate_random_letters(10) # Adjust the number of letters as needed
  end

  def score
    word = params[:word].upcase
    letters = params[:letters]

    if valid_word?(word) && valid_letters?(word, letters)
      @score = calculate_score(word)
      # render turbo_stream: turbo_stream.replace('score_result', partial: 'score_result')
    else
      @score = 0
      @error_message = "Invalid word or letters."
      # render turbo_stream: turbo_stream.replace('score_result', partial: 'score_result')
    end
  end


  private

  def valid_word?(word)
    # response = Net::HTTP.get(uri)
    # serialized_beatles = URI.open(filepath).read
    # JSON.parse(serialized_beatles)
    response = URI.open("https://wagon-dictionary.herokuapp.com/#{word}")
    json = JSON.parse(response.read)
    json['found']
  end

  def valid_letters?(word, letters)
    return false if letters.nil?

    word.chars.all? { |char| word.count(char) <= (letters.count(char) || 0) }
  end

  def calculate_score(word)
    time_penalty = 0 # Implement your own time penalty rules
    length_bonus = word.length
    total_score = length_bonus - time_penalty
    total_score.positive? ? total_score : 0
  end

  # def fetch_word_info(word)
  #   # filepath = "https://wagon-dictionary.herokuapp.com/#{word}"
  #   # response = Net::HTTP.get(uri)
  #   # serialized_beatles = URI.open(filepath).read
  #   # JSON.parse(serialized_beatles)
  #   response = URI.open("https://wagon-dictionary.herokuapp.com/#{word}")
  #   json = JSON.parse(response.read)
  #   json['found']
  # end

  def generate_random_letters(count)
    ('A'..'Z').to_a.sample(count).join
  end
end

app/controllers/scores_controller.rb
require 'net/http'
require 'json'
require 'open-uri'

class ScoresController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/games/score.html.erb
  <div class="container">
    <div class="card score-result">
      <h1>Score</h1>

      <% if @score.positive? %>
        <p class="score-text">Your score: <%= @score %></p>
      <% else %>
        <p class="error-text">Error: <%= @error_message %></p>
      <% end %>

      <%= link_to "Try Again", games_settings_path, class: "try-again-link" %>
    </div>
  </div>

app/views/games/settings.html.erb
  <div class="container-bla">
    <div class="card">
      <h1>Game Settings</h1>

      <p>Random Letters:</p>

      <div class="random-letters">
        <% @letters.chars.each do |letter| %>
          <span class="badge bg-primary random-letter-badge"><%= letter %></span>
        <% end %>
      </div>

      <%= form_tag("/scores/score", method: "post", data: { turbo: 'false' }) do %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <%= hidden_field_tag :letters, @letters %>
        <div class="input-group">
          <%= text_field_tag :word, nil, class: "form-control", placeholder: "Enter your word" %>
          <%= submit_tag "Play", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'application' %>
    <%= stylesheet_link_tag 'game_result_styles' %>
    <%= turbo_frame_tag 'turbo-frame' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scores/_score_result.html.erb
<%= turbo_stream.replace 'score_result' do %>
  <h1>Score</h1>

  <% if @score.positive? %>
    <p>Your score: <%= @score %></p>
  <% else %>
    <p>Error: <%= @error_message %></p>
  <% end %>

  <%= link_to "Try Again", games_settings_path %>
<% end %>

app/views/scores/result.html.erb
<%= render partial: 'score_result' %>

app/views/scores/score.html.erb
<h1>Score</h1>

<% if @score.positive? %>
  <p>Your score: <%= @score %></p>
<% else %>
  <p>Error: <%= @error_message %></p>
<% end %>

<%= link_to "Try Again", games_settings_path %>